### ISSUE TITLE
setting ZEEBE_BROKER_GATEWAY_ENABLE env variable true has no effect

### ISSUE THREAD

**Issue by CodechCFA** [camunda-community-hub/zeebe-cluster-helm#100]
When setting

```
- name: ZEEBE_BROKER_GATEWAY_ENABLE
  value: "true"
```

in the env section of the values.yaml file, this has no effect and the value of that environment variable stays set to false. Setting other env variables works fine.

**Comment by salaboy** [comment]
@CodechCFA can you please share how are you actually setting that up in the `env` section? 
Can you also run `helm template` to see the output `yaml` of the templates? Usually with that you can see what is being replaced and how.

**Comment by CodechCFA** [comment]
I'm setting the environment variable in the env section

```
env:
  - name: ZEEBE_GATEWAY_MONITORING_ENABLED
    value: "true"
  - name: ZEEBE_BROKER_GATEWAY_MONITORING_ENABLED
    value: "true"
  - name: ZEEBE_BROKER_GATEWAY_ENABLE
    value: "true"
```

What happens is all of my env variables get set correctly except for `ZEEBE_BROKER_GATEWAY_ENABLE`. Since this env variable is being hardcoded to false in the statefulset of the broker, the `helm template` output shows as it doubling up on this env var, which looks like helm ends up ignoring the second definition and staying with the first definition of "false". I'm currently working around it by just going into the statefulset template and setting the hardcoded value to true.
