### ISSUE TITLE
How to disable the Elasticsearch Exporter?

### ISSUE THREAD

**Issue by falko** [camunda-community-hub/zeebe-cluster-helm#109]
`elasticsearch.enabled: false` only disables the installation of the Elasticsearch cluster but I would like to also disable the Elasticsearch Exporter which is enabled by default in Zeebe.

I tried with `zeebeCfg: { exporters: {} }`, `zeebeCfg: { exporters: { elasticsearch: {} } }`, and
```yaml
env:
  - name: ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_CLASSNAME
    value: ""
```
but it either kept starting the exporter or ended in a crash-loop.
