### ISSUE TITLE
Values file for Docker for Windows Kubernetes Cluster

### ISSUE THREAD

**Issue by andylholloway** [camunda-community-hub/zeebe-cluster-helm#22]
Hi 
I recently posted a message on your forum about how I couldn't run Zeebe and ElasticSearch in a local kubernetes cluster: https://forum.zeebe.io/t/docker-desktop-kubernetes/949/2

After a bit of trial and error I have been able to get a single instance of Zeebe and ElasticSearch to run in a local Kubernetes cluster. It would be really helpful if the zeebe-cluster-helm chart included a values file like the one I have copied below, to enable developers to deploy Zeebe to a local Kubernetes cluster. I have only tested this in Docker for Windows, but I assume it could also work in Docker for Mac. It is also worth mentioning that ElasticSearch pod can sometimes fail, but not sure why.

**[local-values.yaml]**
```
pvcSize: "4096m"
pvcStorageClassName: "zeebe-storage"
clusterSize: "1"
partitionCount: "1"
replicationFactor: "1"
cpuThreadCount: "1"
ioThreadCount: "1"
elasticsearch:
  imageTag: "7.5.2"
  antiAffinity: "soft"
  volumeClaimTemplate:
   accessModes: [ "ReadWriteOnce" ]
   storageClassName: "es-storage"
   resources:
     requests:
       storage: "1Gi"
  replicas: "1"
  extraInitContainers: |
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: elasticsearch-master
          mountPath: /usr/share/elasticsearch/data
      - name: increase-vm-max-map
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: increase-fd-ulimit
        image: busybox
        command: ["sh", "-c", "ulimit -n 65536"]
        securityContext:
          privileged: true
  clusterHealthCheckParams: "wait_for_status=yellow&timeout=1s" # Required because there are no replicas.
```
Also required are the following **Persistent Volume templates**:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-volume
  labels:
    type: local
spec:
  storageClassName: es-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/usr/share/elasticsearch/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zeebe-volume
  labels:
    type: local
spec:
  storageClassName: zeebe-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/zdata"
```

**[Docker version]**
```
docker version
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:37 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
 Kubernetes:
  Version:          v1.15.5
  StackAPI:         Unknown
```
**[Allocated Resources]**
CPUs: 4
Memory: 8GB
Swap: 1.5GB
Disk image size: 64GB
