### ISSUE TITLE
Setting pvcSize not having effect

### ISSUE THREAD

**Issue by patrykwegrzyn** [camunda-community-hub/zeebe-cluster-helm#77]
Looks like setting `pvcSize` do not work as intended 
Steps to reproduce
set `pvcSize: "1Gi"` in values.yaml

Result 
Cluster size remains at default  `10Gi`

**Comment by salaboy** [comment]
@patrykwegrzyn can you share your values file? Also which chart are you using? `zeebe-cluster` or `zeebe-full` ?

**Comment by patrykwegrzyn** [comment]
hi there it was `zeebe-full`

```
# Default values for zeebe-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global: 
  elasticsearch:
    host: "elasticsearch-master"
    port: 9200 
  zeebe: "{{ .Release.Name }}-zeebe"
clusterSize: "1"
partitionCount: "1"
replicationFactor: "1"
cpuThreadCount: "2"
ioThreadCount: "2"
pvcSize: "1Gi"
pvcAccessModes: [ "ReadWriteOnce" ]
pvcStorageClassName: "longhorn-test"
env: []
gateway:
  replicas: 1
  logLevel: warn
elasticsearch:
  enabled: false
  imageTag: 6.8.5
kibana:
  enabled: false
  imageTag: 6.8.5
prometheus:
  enabled: false
  servicemonitor:
    enabled: false
JavaOpts: |
  -XX:+UseParallelGC 
  -XX:MinHeapFreeRatio=5
  -XX:MaxHeapFreeRatio=10
  -XX:MaxRAMPercentage=25.0 
  -XX:GCTimeRatio=4 
  -XX:AdaptiveSizePolicyWeight=90
  -XX:+PrintFlagsFinal
  -Xmx4g
  -Xms4g
  -XX:+HeapDumpOnOutOfMemoryError
  -XX:HeapDumpPath=/usr/local/zeebe/data
  -XX:ErrorFile=/usr/local/zeebe/data/zeebe_error%p.log
image:
  repository: camunda/zeebe
  tag: 0.22.1
  pullPolicy: IfNotPresent
labels:
  app: zeebe    
serviceType: ClusterIP
serviceHttpPort: 9600
serviceGatewayPort: 26500    
serviceCommandPort: 26501     
serviceInternalPort: 26502  
resources: 
  requests:
    cpu: 500m
    memory: 2Gi
  limits:
    cpu: 1000m
    memory: 4Gi
probePath: /ready
readinessProbe:
  failureThreshold: 1
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
nodeSelector: {}
tolerations: []
affinity: {}
```

**Comment by salaboy** [comment]
@patrykwegrzyn if you are using `zeebe-full` you need to set the parameters in the right hierarchy. As you are setting the parameters for the `zeebe-cluster` sub chart you need to have an entry in your yaml file respecting that hierarchical relationship. Your yaml should look like this: 

```
global: 
  elasticsearch:
    host: "elasticsearch-master"
    port: 9200 
  zeebe: "{{ .Release.Name }}-zeebe"
zeebe:
  clusterSize: "1"
  partitionCount: "1"
  replicationFactor: "1"
  cpuThreadCount: "2"
  ioThreadCount: "2"
  pvcSize: "1Gi"
  pvcAccessModes: [ "ReadWriteOnce" ]
  pvcStorageClassName: "longhorn-test"
  env: []
  gateway:
    replicas: 1
    logLevel: warn
  elasticsearch:
    enabled: false
    imageTag: 6.8.5
  kibana:
    enabled: false
    imageTag: 6.8.5
  prometheus:
    enabled: false
    servicemonitor:
      enabled: false
  JavaOpts: |
  -XX:+UseParallelGC 
  -XX:MinHeapFreeRatio=5
  -XX:MaxHeapFreeRatio=10
  -XX:MaxRAMPercentage=25.0 
  -XX:GCTimeRatio=4 
  -XX:AdaptiveSizePolicyWeight=90
  -XX:+PrintFlagsFinal
  -Xmx4g
  -Xms4g
  -XX:+HeapDumpOnOutOfMemoryError
  -XX:HeapDumpPath=/usr/local/zeebe/data
  -XX:ErrorFile=/usr/local/zeebe/data/zeebe_error%p.log
  image:
    repository: camunda/zeebe
    tag: 0.22.1
    pullPolicy: IfNotPresent
  labels:
    app: zeebe    
  serviceType: ClusterIP
  serviceHttpPort: 9600
  serviceGatewayPort: 26500    
  serviceCommandPort: 26501     
  serviceInternalPort: 26502  
  resources: 
    requests:
      cpu: 500m
      memory: 2Gi
    limits:
      cpu: 1000m
      memory: 4Gi
  probePath: /ready
  readinessProbe:
    failureThreshold: 1
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  nodeSelector: {}
  tolerations: []
  affinity: {}
```
